FROM ubuntu:16.04
MAINTAINER shoulderhu@gmail.com

RUN apt update
RUN apt -y install quagga net-tools telnet

RUN echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
RUN sysctl -p

RUN sed -i 's/zebra=no/zebra=yes/'  /etc/quagga/daemons
RUN sed -i 's/bgpd=no/bgpd=yes/'  /etc/quagga/daemons

COPY command-quagga.sh .