FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends quagga net-tools telnet && \
    rm -rf /var/lib/apt/lists/*

RUN echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
RUN sysctl -p

RUN sed -i 's/zebra=no/zebra=yes/'  /etc/quagga/daemons
RUN sed -i 's/bgpd=no/bgpd=yes/'  /etc/quagga/daemons

COPY command-router.sh .